### ISSUE TITLE
agenda: multi-threading support in 3.4

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4649]
Release 3.4a3:
* [x] Bug fixes for async progress
* [x] Granular locks, ref:  #4425 #4472
* [x] Per-VCI Request pool. ref: #4285 #4499 #4550 
* [x] Per-VCI Progress. ref: #4618 [In Review]
* [x] Enable multiple-vci in OFI netmod. ref: #4590 
* [x] Multiple-VCI for collectives, ref: #4650
* [x] Enable multiple-vci in UCX netmod, ref: #4648 

Release 3.4
* [ ] MUltiple-VCI for active messages
* [x] Multiple-VCI for RMA. ref: #4746 #4756 #4770
* [x] New scheme for UCX active messages. ref: #4713

**Comment by hzhou** [comment]
Multiple-VCI for active messages is on-going. Meanwhile, this ticket served its purpose of tracking progress during 3.4 development. Thus closing it.
