### ISSUE TITLE
ABI: Fortran ABI TODO

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#6948]
The next step for MPI ABI after swappable `libmpi.so` is to make `libmpifort.so`  swappable. This issue is for discussion and tracking todo list.

## TODO list
* [ ] Add to Fortran binding scripts to generate ABI versions based on ABI header `mpi_abi.h`
* F77
    * [ ]  MPI Calls are directly linked to named-mangled symbols -- nothing to be done, but double check
    * [ ] Need standardize common blocks names. Currently it is like 
```
00000000000d3570 B mpifcmb5_
00000000000d3560 B mpifcmb9_
00000000000d3550 B mpifcmba_
```    
* F90
    * [ ] Double check
* F08
    * [ ] Remove the internal modules
       The symbols are tied to the module name, e.g. `__mpi_f08_callbacks_MOD_mpi_comm_dup_fn`. It need be `__mpi_f08_MOD_mpi_comm_dup_fn`

## Discussion
Hmm, likely there will be more issues. Fortran ABI will likely require standardizing Fortran binding implementation. I think it is more sensible to release a stand-alone `libmpifort_abi.so` that is built on top of `libmpi_abi.so`

**Comment by dalcinl** [comment]
> it is more sensible to release a stand-alone `libmpifort_abi.so` that is built on top of `libmpi_abi.so`

Definitely. Moreover, you better do not mess with the current internal Fortran module names or you will break the MPICH ABI for Fortran users in a really bad way (unless Fortran is not covered by the MPICH ABI initiative?).

**Comment by hzhou** [comment]
> > it is more sensible to release a stand-alone `libmpifort_abi.so` that is built on top of `libmpi_abi.so`
> 
> Definitely. Moreover, you better do not mess with the current internal Fortran module names or you will break the MPICH ABI for Fortran users in a really bad way (unless Fortran is not covered by the MPICH ABI initiative?).

That's okay. The new ABI is an opt-in.

**Comment by hzhou** [comment]
Closing this issue. Follow https://github.com/pmodels/mpich/pull/6953 for Fortran binding on top of MPI ABI.
